kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager
data:
  config.yml: |-
    global:
      resolve_timeout: 5m

    route:
      receiver: 'slack-notifications'
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 1h

    receivers:
      - name: 'slack-notifications'
        slack_configs:
        - api_url: 'https://hooks.slack.com/services/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'
          channel: '#alert-messages'
          send_resolved: true
          title: "{{ template \"slack.default.title\" . }}"
          text: "{{ template \"slack.default.text\" . }}"

  configure_secret.sh: |-
    echo 'Configuring Slack hook url.'
    sed -i -e s,API_URL_SECRET,"$SLACK_HOOK_URL",g /etc/alertmanager/config.yml
    exec /bin/alertmanager $*
