apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      initContainers:
      - name: init-alertmanager
        image: busybox
        command: ['sh', '-c', 'cp /etc/alertmanager/* /alertmanager/ && sed -i s,API_URL_SECRET,"$SLACK_HOOK_URL",g /alertmanager/config.yml']
        volumeMounts:
        - name: config-volume
          mountPath: /etc/alertmanager
        - name: config-dir
          mountPath: /alertmanager
        env:
        - name: SLACK_HOOK_URL
          valueFrom:
            secretKeyRef:
              name: slack-hook-url
              key: slack-hook-url

      containers:
      - name: alertmanager
        image: prom/alertmanager:latest
        command: ['/bin/alertmanager']
        args:
          - '--config.file=/alertmanager/config.yml'
          - '--storage.path=/alertmanager'
        ports:
        - name: alertmanager
          containerPort: 9093
        volumeMounts:
        - name: config-dir
          mountPath: /alertmanager
      volumes:
      - name: config-volume
        configMap:
          name: alertmanager
      - name: config-dir
        emptyDir: {}
